/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as Top100RouteImport } from './routes/top-100'
import { Route as SongsRouteImport } from './routes/songs'
import { Route as SearchRouteImport } from './routes/search'
import { Route as NewsRouteImport } from './routes/news'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AwardsRouteImport } from './routes/awards'
import { Route as ArtistsRouteImport } from './routes/artists'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AlbumsRouteImport } from './routes/albums'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SongsIdRouteImport } from './routes/songs.$id'
import { Route as ChartsSlugRouteImport } from './routes/charts.$slug'
import { Route as ArtistsIdRouteImport } from './routes/artists.$id'
import { Route as AlbumsIdRouteImport } from './routes/albums.$id'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const Top100Route = Top100RouteImport.update({
  id: '/top-100',
  path: '/top-100',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsRoute = SongsRouteImport.update({
  id: '/songs',
  path: '/songs',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsRoute = ArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsRoute = AlbumsRouteImport.update({
  id: '/albums',
  path: '/albums',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsIdRoute = SongsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SongsRoute,
} as any)
const ChartsSlugRoute = ChartsSlugRouteImport.update({
  id: '/charts/$slug',
  path: '/charts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsIdRoute = ArtistsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ArtistsRoute,
} as any)
const AlbumsIdRoute = AlbumsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AlbumsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/albums': typeof AlbumsRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/artists': typeof ArtistsRouteWithChildren
  '/awards': typeof AwardsRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/search': typeof SearchRoute
  '/songs': typeof SongsRouteWithChildren
  '/top-100': typeof Top100Route
  '/trending': typeof TrendingRoute
  '/videos': typeof VideosRoute
  '/albums/$id': typeof AlbumsIdRoute
  '/artists/$id': typeof ArtistsIdRoute
  '/charts/$slug': typeof ChartsSlugRoute
  '/songs/$id': typeof SongsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/albums': typeof AlbumsRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/artists': typeof ArtistsRouteWithChildren
  '/awards': typeof AwardsRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/search': typeof SearchRoute
  '/songs': typeof SongsRouteWithChildren
  '/top-100': typeof Top100Route
  '/trending': typeof TrendingRoute
  '/videos': typeof VideosRoute
  '/albums/$id': typeof AlbumsIdRoute
  '/artists/$id': typeof ArtistsIdRoute
  '/charts/$slug': typeof ChartsSlugRoute
  '/songs/$id': typeof SongsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/albums': typeof AlbumsRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/artists': typeof ArtistsRouteWithChildren
  '/awards': typeof AwardsRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/search': typeof SearchRoute
  '/songs': typeof SongsRouteWithChildren
  '/top-100': typeof Top100Route
  '/trending': typeof TrendingRoute
  '/videos': typeof VideosRoute
  '/albums/$id': typeof AlbumsIdRoute
  '/artists/$id': typeof ArtistsIdRoute
  '/charts/$slug': typeof ChartsSlugRoute
  '/songs/$id': typeof SongsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/albums'
    | '/analytics'
    | '/artists'
    | '/awards'
    | '/login'
    | '/news'
    | '/search'
    | '/songs'
    | '/top-100'
    | '/trending'
    | '/videos'
    | '/albums/$id'
    | '/artists/$id'
    | '/charts/$slug'
    | '/songs/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/albums'
    | '/analytics'
    | '/artists'
    | '/awards'
    | '/login'
    | '/news'
    | '/search'
    | '/songs'
    | '/top-100'
    | '/trending'
    | '/videos'
    | '/albums/$id'
    | '/artists/$id'
    | '/charts/$slug'
    | '/songs/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/albums'
    | '/analytics'
    | '/artists'
    | '/awards'
    | '/login'
    | '/news'
    | '/search'
    | '/songs'
    | '/top-100'
    | '/trending'
    | '/videos'
    | '/albums/$id'
    | '/artists/$id'
    | '/charts/$slug'
    | '/songs/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AlbumsRoute: typeof AlbumsRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  ArtistsRoute: typeof ArtistsRouteWithChildren
  AwardsRoute: typeof AwardsRoute
  LoginRoute: typeof LoginRoute
  NewsRoute: typeof NewsRoute
  SearchRoute: typeof SearchRoute
  SongsRoute: typeof SongsRouteWithChildren
  Top100Route: typeof Top100Route
  TrendingRoute: typeof TrendingRoute
  VideosRoute: typeof VideosRoute
  ChartsSlugRoute: typeof ChartsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top-100': {
      id: '/top-100'
      path: '/top-100'
      fullPath: '/top-100'
      preLoaderRoute: typeof Top100RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs': {
      id: '/songs'
      path: '/songs'
      fullPath: '/songs'
      preLoaderRoute: typeof SongsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards': {
      id: '/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists': {
      id: '/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof ArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums': {
      id: '/albums'
      path: '/albums'
      fullPath: '/albums'
      preLoaderRoute: typeof AlbumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/$id': {
      id: '/songs/$id'
      path: '/$id'
      fullPath: '/songs/$id'
      preLoaderRoute: typeof SongsIdRouteImport
      parentRoute: typeof SongsRoute
    }
    '/charts/$slug': {
      id: '/charts/$slug'
      path: '/charts/$slug'
      fullPath: '/charts/$slug'
      preLoaderRoute: typeof ChartsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/$id': {
      id: '/artists/$id'
      path: '/$id'
      fullPath: '/artists/$id'
      preLoaderRoute: typeof ArtistsIdRouteImport
      parentRoute: typeof ArtistsRoute
    }
    '/albums/$id': {
      id: '/albums/$id'
      path: '/$id'
      fullPath: '/albums/$id'
      preLoaderRoute: typeof AlbumsIdRouteImport
      parentRoute: typeof AlbumsRoute
    }
  }
}

interface AlbumsRouteChildren {
  AlbumsIdRoute: typeof AlbumsIdRoute
}

const AlbumsRouteChildren: AlbumsRouteChildren = {
  AlbumsIdRoute: AlbumsIdRoute,
}

const AlbumsRouteWithChildren =
  AlbumsRoute._addFileChildren(AlbumsRouteChildren)

interface ArtistsRouteChildren {
  ArtistsIdRoute: typeof ArtistsIdRoute
}

const ArtistsRouteChildren: ArtistsRouteChildren = {
  ArtistsIdRoute: ArtistsIdRoute,
}

const ArtistsRouteWithChildren =
  ArtistsRoute._addFileChildren(ArtistsRouteChildren)

interface SongsRouteChildren {
  SongsIdRoute: typeof SongsIdRoute
}

const SongsRouteChildren: SongsRouteChildren = {
  SongsIdRoute: SongsIdRoute,
}

const SongsRouteWithChildren = SongsRoute._addFileChildren(SongsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AlbumsRoute: AlbumsRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  ArtistsRoute: ArtistsRouteWithChildren,
  AwardsRoute: AwardsRoute,
  LoginRoute: LoginRoute,
  NewsRoute: NewsRoute,
  SearchRoute: SearchRoute,
  SongsRoute: SongsRouteWithChildren,
  Top100Route: Top100Route,
  TrendingRoute: TrendingRoute,
  VideosRoute: VideosRoute,
  ChartsSlugRoute: ChartsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
